# Generated by Django 3.0.4 on 2020-05-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstatus', '0002_auto_20200503_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
