# Generated by Django 3.0.4 on 2020-05-04 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userstatus', '0003_status_is_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='is_liked',
        ),
    ]
